### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by rohitsrepo** [rohitsrepo/growth#20]

**Comment by tanuj979** [comment]
Beauty Link on around you page opens india/all/all (should pick the city and locality or at least the city from the URL)

Breadcrumb separators are not visible - Pulkit please fix this for all pages like you did for the attributes page.

City and locality is still not being picked in around you page from the URL

Taglines on homepage are not in sync with the pics - will give the relevant content

Footer links on mobile are not clickable under the magicpin dropdown (It was working fine before, why did this happen?)

Around you page on mobile breaks when the navigation dropdown is opened

If any merchant's logo / cover pic is not uploaded by the content team, we should show a default image in place of that

Mobile website - Navigation menu - once opened for dropdown, does not closes

Pagination structure on around you page is breaking on mobile

If we know that the main locality of the sub locality / landmark, the page title should be "Best Restaurants in <Sublocality>, <Locality>, <City>

More relevant filter options for these pages

Please check if the distance threshold is 2 Kms for the data being displayed. If there is no data for this distance, we should not display the sub locality.
